name: CMake

on:
  push:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type: [Debug, Release]

    steps:
    - uses: actions/checkout@v3

    - name: Environment setup
      run: sudo tools/installers/essentials.sh

    - name: Configure CMake
      # run: cmake -B ${{github.workspace}}/build/masscalculator-docker-${{matrix.build_type}} -G Ninja -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
      # @todo(jimmyhalimi): Update stages that are in progress.
      run: echo 'Deploy stage is in progress'

    - name: Build
      # run: cmake --build ${{github.workspace}}/build/masscalculator-docker-${{matrix.build_type}} -t build-masscalculator-core-docker --config ${{matrix.build_type}}
      # @todo(jimmyhalimi): Update stages that are in progress.
      run: echo 'Deploy stage is in progress'

    - name: Run
      # run: cmake --build ${{github.workspace}}/build/masscalculator-docker-${{matrix.build_type}} -t run-masscalculator-core-docker --config ${{matrix.build_type}}
      # @todo(jimmyhalimi): Update stages that are in progress.
      run: echo 'Deploy stage is in progress'

    - name: Deploy
      # @todo(jimmyhalimi): Update stages that are in progress.
      run: echo 'Deploy stage is in progress'

  trigger:
    runs-on: ubuntu-latest
    needs: build
    if: github.event.pull_request.merged == true

    steps:
      - name: Send repository dispatch event
        uses: peter-evans/repository-dispatch@v1
        with:
          repository: MassCalculator/masscalculator.github.io
          event-type: masscalculator-cli-pr-merged
          token: ${{secrets.MASSCALCULATOR_SECRET}}
